
@startuml
skinparam backgroundColor white

skinparam component {
   FontSize 13
  BackgroundColor<<Apache>> #9B79F6
  BorderColor<<Apache>> #FFC57A
  FontName Inter
FontColor #AF5339
  BorderColor #F8D898

  BackgroundColor #FEF9F0
  ArrowFontName Impact

  ArrowColor #9B79F6
  ArrowFontColor #777777
}
[A] as "<color:white>Panneau Photovoltaïque</color>" #9B79F6


[Énergie solaire] -right-> [A]
[Fournisseurs d'électricité] -left-> [A]
[Data Centers] -left-> [A]

[Météo] -down-> [A]
[Réglementation] -down-> [A]
[Réseau électrique] -down-> [A]
[Fabricants] -up-> [A]
[Techniciens] -up-> [A]
[Project Managers] -up-> [A]
[Onduleurs] -up-> [A]
[Monture] -up-> [A]
[Dispositifs de protection] -up-> [A]
[Batteries] -up-> [A]
[Compteurs] -up-> [A]
[Transformateurs] -up-> [A]
[Isolateurs] -up-> [A]

@enduml