@startuml

skinparam component {
  FontSize 13
 
  FontName Inter




  ArrowColor #C363A0
  ArrowFontColor #222
}
skinparam actor {
  FontSize 13
 
  FontName Inter

FontColor #C363A0

  BackgroundColor #F0EEFF/C363A0


}
skinparam participant {
  FontSize 13
 
  FontName Inter


FontColor #5448a2
  BorderColor #7359CC

  BackgroundColor #F3F1FF



  ArrowColor #C363A0
  ArrowFontColor #222
participant "Panneau Solaire" FontColor #fff
}
participant "Energie Solaire" as es
actor Fabricants 

actor Techniciens 
participant "<color:#white>Panneau Solaire" as ps  #C363A0/C363A0
participant Tracker 
participant Onduleurs
participant Batteries
participant "Régulateur de Charge" as rc
participant Transformateurs

participant "Réseau Électrique" as re
participant Compteurs 
actor "Ingénieurs Systèmes" as is
participant "Data Centers" as dc
participant "Fournisseurs d'Électricité" as fe

Fabricants -> ps : Fabriquer le panneau solaire
Techniciens -> ps : Installer le panneau solaire
Tracker -> ps : Orienter le panneau solaire
es -> ps : Envoyer énergie solaire
ps -> Onduleurs : Convertir courant continu en alternatif
Onduleurs -> Batteries : Stocker l'énergie excédentaire
Batteries -> rc : Gérer le stockage et éviter la surcharge
rc -> Batteries : Réguler le niveau de charge
ps -> Transformateurs : Adapter la tension pour le réseau
ps -> Compteurs : Mesurer l'énergie produite
Compteurs -> is : Transmettre les données de production
is -> ps : Suivi et optimisation de la production d'énergie
ps -> re :  Injecter l'énergie excédentaire
re -> fe : Racheter l'énergie excédentaire
fe -> re : Retourner les paiements ou crédits

re -> dc : Fournir de l'énergie en cas de besoin
dc -> ps : Consommer l'énergie produite
@enduml