@startuml
skinparam backgroundColor white

skinparam component {
  FontSize 13
  BackgroundColor<<Apache>> #F0EEFF
  BorderColor<<Apache>> #FFC57A
  FontName Inter
FontColor #7664E1
  BorderColor #7359CC

  BackgroundColor #F0EEFF
  ArrowFontName Impact

  ArrowColor #C363A0
  ArrowFontColor #777777
}
[A] as "<color:white>Panneau Photovoltaïque</color>" #E54871


[Énergie solaire] -right-> [A]
[Fournisseurs d'électricité] -left-> [A]
[Data Centers] -left-> [A]

[Météo] -down-> [A]
[Réglementation] -down-> [A]
[Réseau électrique] -down-> [A]
[Fabricants] -up-> [A]
[Techniciens] -up-> [A]
[Project Managers] -up-> [A]
[Onduleurs] -up-> [A]
[Monture] -up-> [A]
[Dispositifs de protection] -up-> [A]
[Batteries] -up-> [A]
[Compteurs] -up-> [A]
[Transformateurs] -up-> [A]
[Isolateurs] -up-> [A]

@enduml